# Stage 1: Build
FROM node:18-alpine AS builder
WORKDIR /app
COPY backend/package*.json ./
RUN npm install --only=production
COPY backend/. .

# Stage 2: Run
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 3000
CMD ["node", "server.js"]